### ISSUE TITLE
Kodi-Webbrowser-Addon

### ISSUE THREAD

**Issue by tgez** [AlwinEsch/web.browser.chromium#2]
Sehr geehrter Herr Alwin Esch,

ich warte lange auf die Finalversion von Kodi-Web-Addon, habe aber schon lange von ihnen nichts gehört, arbeiten Sie noch an diesem projekt ? in dem letzten Video von Kodi-Webbrowser sah alles gut aus (sogar mehr als gut) Sie können wenigstens eine Beta Version als Addon rausbringen damit wir testen können. 
Vielen vielen Dank an ihre Mühe und Respekt das Sie sowas in Kodi realisieren.

Mit freundlichen Grüßen

**Comment by tgez** [comment]
hello Alwin,

please publish a Beta Version of Kodi-Web-Browser-Addon, so that we can test it !


Regards

tgez

**Comment by timotoots** [comment]
Yes, there is definitely interest in it! I have idea to use Kodi as a base for an another project and API controllable web browser is exactly missing..

**Comment by AlwinEsch** [comment]
Still want to bring, but first must be the basic system in Kodi improved. Is a bit harter story, but has now created a new request in Kodi to improve the basics for this.

**Comment by AlwinEsch** [comment]
Sorry that's take so long.

**Comment by AlwinEsch** [comment]
Is in progress and hopefully on next Kodi DevCon finished.
